### ISSUE TITLE
【依頼】ChatSpace挙動確認

### ISSUE THREAD

**Issue by T-Yuto** [T-Yuto/chat-space#29]
＃IPアドレス
54.150.204.11

**Comment by yasunamiura** [comment]
竹村さん、ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

[修正箇所]
①サイドバーの最新メッセージの文字サイズを小さくしましょう
<img width="290" alt="ChatSpace" src="https://user-images.githubusercontent.com/52514431/80794967-349a2180-8bd6-11ea-8a4b-914dde30ca30.png">
模範
<img width="755" alt="ChatSpace_フロント実装" src="https://user-images.githubusercontent.com/52514431/80794996-48458800-8bd6-11ea-9a0b-639b03030b76.png">


修正し次第、以下のChatSpace完了報告フォームに再度こちらのissueのURLを記載していただき提出お願いします！
※新しいissueを作っていただく必要はありません
https://docs.google.com/forms/d/e/1FAIpQLSfNKbknajjCthhkGSyIkhspu2hOAxnESHweNLX2LQJdlO5vGw/viewform

**Comment by yasunamiura** [comment]
ご提出ありがとうございます！
確認させて頂きましたが、修正箇所ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！
